export // Mock product data based on your product schema
const mockProducts = [
  {
    _id: "1",
    name: "Premium African Print Dress",
    description:
      "Beautiful African print dress with modern design, perfect for special occasions and traditional ceremonies.",
    price: 25000,
    originalPrice: 30000,
    mainImage: "/product-1.jpg",
    subImages: ["/product-1-1.jpg", "/product-1-2.jpg"],
    category: "women",
    type: "traditional",
    status: "pending",
    isAdminApproved: false,
    rejectionReason: "",
    stock: 15,
    sku: "AFR-DRESS-001",
    materials: "100% African Wax Print Cotton",
    careInstructions: "Hand wash cold, line dry, iron low heat",
    deliveryInfo: "Ready to ship in 2-3 business days",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red/Black", "Blue/Gold", "Green/Orange"],
    attributes: {
      Season: "All Season",
      Occasion: "Traditional",
      Style: "Modern African",
    },
    stylist: {
      _id: "1",
      name: "Amina Couture",
      company: "Amina Couture Designs",
      verificationStatus: "verified",
    },
    createdAt: "2024-03-18T10:30:00Z",
    updatedAt: "2024-03-18T10:30:00Z",
    isBestSeller: false,
    isNewProduct: true,
    featured: false,
    rating: 0,
    reviewCount: 0,
  },
  {
    _id: "2",
    name: "Men's Corporate Agbada",
    description:
      "Elegant Agbada set for corporate events and formal occasions. Made with premium quality fabric.",
    price: 45000,
    originalPrice: 50000,
    mainImage: "/product-2.jpg",
    subImages: ["/product-2-1.jpg", "/product-2-2.jpg"],
    category: "men",
    type: "corporate",
    status: "pending",
    isAdminApproved: false,
    rejectionReason: "",
    stock: 8,
    sku: "MEN-AGBADA-001",
    materials: "Premium Cotton Blend",
    careInstructions: "Dry clean only",
    deliveryInfo: "Made to order - 7-10 business days",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Navy Blue", "Charcoal Gray", "Burgundy"],
    attributes: {
      Season: "All Season",
      Occasion: "Corporate",
      Style: "Traditional Formal",
    },
    stylist: {
      _id: "2",
      name: "John Fashion",
      company: "John Fashion House",
      verificationStatus: "pending",
    },
    createdAt: "2024-03-19T14:20:00Z",
    updatedAt: "2024-03-19T14:20:00Z",
    isBestSeller: false,
    isNewProduct: true,
    featured: false,
    rating: 0,
    reviewCount: 0,
  },
  {
    _id: "3",
    name: "Casual Kaftan Dress",
    description:
      "Comfortable and stylish kaftan dress for everyday wear. Lightweight and perfect for warm weather.",
    price: 18000,
    originalPrice: 22000,
    mainImage: "/product-3.jpg",
    subImages: ["/product-3-1.jpg", "/product-3-2.jpg"],
    category: "women",
    type: "casual",
    status: "pending",
    isAdminApproved: false,
    rejectionReason: "",
    stock: 25,
    sku: "WOM-KAFTAN-001",
    materials: "Lightweight Cotton",
    careInstructions: "Machine wash cold, tumble dry low",
    deliveryInfo: "Ready to ship in 1-2 business days",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Blue", "Pink", "Yellow"],
    attributes: {
      Season: "Summer",
      Occasion: "Casual",
      Style: "Relaxed Fit",
    },
    stylist: {
      _id: "1",
      name: "Amina Couture",
      company: "Amina Couture Designs",
      verificationStatus: "verified",
    },
    createdAt: "2024-03-20T09:15:00Z",
    updatedAt: "2024-03-20T09:15:00Z",
    isBestSeller: false,
    isNewProduct: true,
    featured: false,
    rating: 0,
    reviewCount: 0,
  },
  {
    _id: "4",
    name: "Traditional Senator Outfit",
    description:
      "Classic senator outfit with intricate embroidery details. Perfect for weddings and ceremonies.",
    price: 35000,
    originalPrice: 40000,
    mainImage: "/product-4.jpg",
    subImages: ["/product-4-1.jpg", "/product-4-2.jpg"],
    category: "men",
    type: "traditional",
    status: "rejected",
    isAdminApproved: false,
    rejectionReason: "Product images are low quality and do not meet platform standards",
    stock: 12,
    sku: "MEN-SENATOR-001",
    materials: "Cotton Brocade",
    careInstructions: "Dry clean recommended",
    deliveryInfo: "Ready to ship in 3-5 business days",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Cream", "Gold"],
    attributes: {
      Season: "All Season",
      Occasion: "Traditional",
      Style: "Classic",
    },
    stylist: {
      _id: "3",
      name: "Sarah Styles",
      company: "Sarah Styles Collection",
      verificationStatus: "verified",
    },
    createdAt: "2024-03-17T16:45:00Z",
    updatedAt: "2024-03-18T11:20:00Z",
    isBestSeller: false,
    isNewProduct: true,
    featured: false,
    rating: 0,
    reviewCount: 0,
  },
  {
    _id: "5",
    name: "Modern Blouse and Wrapper Set",
    description: "Contemporary blouse and wrapper set with modern cuts and traditional patterns.",
    price: 22000,
    originalPrice: 28000,
    mainImage: "/product-5.jpg",
    subImages: ["/product-5-1.jpg", "/product-5-2.jpg"],
    category: "women",
    type: "traditional",
    status: "approved",
    isAdminApproved: true,
    rejectionReason: "",
    stock: 20,
    sku: "WOM-BLOUSE-001",
    materials: "African Print Fabric",
    careInstructions: "Hand wash cold, line dry",
    deliveryInfo: "Ready to ship in 2-3 business days",
    sizes: ["S", "M", "L"],
    colors: ["Multi-color", "Blue/White", "Red/Gold"],
    attributes: {
      Season: "All Season",
      Occasion: "Traditional",
      Style: "Modern Traditional",
    },
    stylist: {
      _id: "5",
      name: "Elegance By Zara",
      company: "Elegance By Zara",
      verificationStatus: "verified",
    },
    createdAt: "2024-03-16T13:30:00Z",
    updatedAt: "2024-03-17T10:15:00Z",
    isBestSeller: false,
    isNewProduct: true,
    featured: false,
    rating: 0,
    reviewCount: 0,
  },
];
export const stylistmockProducts = [
  {
    id: "prod-7892",
    name: "Premium Ankara Jumpsuit",
    image: "/product-1.jpg",
    price: 25000,
    stock: 15,
    status: "approved",
    views: 124,
    orders: 18,
  },
  {
    id: "prod-6541",
    name: "Kente Agbada Set",
    image: "/product-2.jpg",
    price: 35000,
    stock: 8,
    status: "approved",
    views: 89,
    orders: 12,
  },
  {
    id: "prod-3214",
    name: "Adire Wrap Dress",
    image: "/product-3.jpg",
    price: 22000,
    stock: 0,
    status: "pending",
    views: 45,
    orders: 0,
  },
];
export const mockUsers = [
  {
    _id: "1",
    name: "John Doe",
    email: "john@example.com",
    avatar: "/user-avatar-1.jpg",
    role: "user",
    status: "active",
    walletBalance: 25000,
    ordersCount: 12,
    createdAt: "2024-01-15T10:30:00Z",
    lastLogin: "2024-03-20T14:25:00Z",
    isEmailVerified: true,
  },
  {
    _id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    avatar: "/user-avatar-2.jpg",
    role: "user",
    status: "active",
    walletBalance: 15000,
    ordersCount: 8,
    createdAt: "2024-02-20T08:15:00Z",
    lastLogin: "2024-03-19T09:45:00Z",
    isEmailVerified: true,
  },
  {
    _id: "3",
    name: "Mike Johnson",
    email: "mike@example.com",
    avatar: "/user-avatar-3.jpg",
    role: "user",
    status: "suspended",
    walletBalance: 5000,
    ordersCount: 3,
    createdAt: "2024-03-01T16:20:00Z",
    lastLogin: "2024-03-18T11:30:00Z",
    isEmailVerified: false,
    suspensionReason: "Violation of terms",
  },
  {
    _id: "4",
    name: "Sarah Wilson",
    email: "sarah@example.com",
    avatar: "/user-avatar-4.jpg",
    role: "user",
    status: "inactive",
    walletBalance: 0,
    ordersCount: 0,
    createdAt: "2024-03-10T12:00:00Z",
    lastLogin: "2024-03-10T12:00:00Z",
    isEmailVerified: false,
  },
  {
    _id: "5",
    name: "David Brown",
    email: "david@example.com",
    avatar: "/user-avatar-5.jpg",
    role: "user",
    status: "active",
    walletBalance: 75000,
    ordersCount: 25,
    createdAt: "2024-01-05T09:45:00Z",
    lastLogin: "2024-03-20T16:10:00Z",
    isEmailVerified: true,
  },
];

export const mockStylists = [
  {
    _id: "1",
    name: "Amina Couture",
    email: "amina@couture.com",
    avatar: "/stylist-avatar-1.jpg",
    company: "Amina Couture Designs",
    role: "stylist",
    verificationStatus: "verified",
    status: "active",
    totalProducts: 24,
    pendingApproval: 3,
    totalOrders: 128,
    totalRevenue: 1250000,
    rating: 4.8,
    reviewCount: 89,
    joinedDate: "2023-11-15T10:30:00Z",
    lastLogin: "2024-03-20T14:25:00Z",
    isEmailVerified: true,
    canAddProducts: true,
    businessInfo: {
      description: "Premium African fashion designs with modern touch",
      location: "Lagos, Nigeria",
      experience: "5 years",
      specialties: ["Traditional", "Corporate", "Casual"],
    },
  },
  {
    _id: "2",
    name: "John Fashion",
    email: "john@fashion.com",
    avatar: "/stylist-avatar-2.jpg",
    company: "John Fashion House",
    role: "stylist",
    verificationStatus: "pending",
    status: "active",
    totalProducts: 12,
    pendingApproval: 5,
    totalOrders: 45,
    totalRevenue: 450000,
    rating: 4.2,
    reviewCount: 23,
    joinedDate: "2024-01-20T08:15:00Z",
    lastLogin: "2024-03-19T09:45:00Z",
    isEmailVerified: true,
    canAddProducts: false,
    businessInfo: {
      description: "Modern and contemporary fashion designs",
      location: "Abuja, Nigeria",
      experience: "3 years",
      specialties: ["Modern", "Casual"],
    },
  },
  {
    _id: "3",
    name: "Sarah Styles",
    email: "sarah@styles.com",
    avatar: "/stylist-avatar-3.jpg",
    company: "Sarah Styles Collection",
    role: "stylist",
    verificationStatus: "verified",
    status: "suspended",
    totalProducts: 36,
    pendingApproval: 0,
    totalOrders: 215,
    totalRevenue: 2100000,
    rating: 4.9,
    reviewCount: 156,
    joinedDate: "2023-08-10T16:20:00Z",
    lastLogin: "2024-03-18T11:30:00Z",
    isEmailVerified: true,
    canAddProducts: false,
    suspensionReason: "Quality compliance issues",
    businessInfo: {
      description: "Luxury fashion and bespoke tailoring",
      location: "Port Harcourt, Nigeria",
      experience: "7 years",
      specialties: ["Luxury", "Bespoke", "Traditional"],
    },
  },
  {
    _id: "4",
    name: "Mike Designs",
    email: "mike@designs.com",
    avatar: "/stylist-avatar-4.jpg",
    company: "Mike Creative Designs",
    role: "stylist",
    verificationStatus: "rejected",
    status: "inactive",
    totalProducts: 8,
    pendingApproval: 8,
    totalOrders: 12,
    totalRevenue: 120000,
    rating: 4.0,
    reviewCount: 8,
    joinedDate: "2024-02-28T12:00:00Z",
    lastLogin: "2024-03-05T12:00:00Z",
    isEmailVerified: true,
    canAddProducts: false,
    rejectionReason: "Incomplete business documentation",
    businessInfo: {
      description: "Creative and innovative fashion solutions",
      location: "Ibadan, Nigeria",
      experience: "2 years",
      specialties: ["Creative", "Modern"],
    },
  },
  {
    _id: "5",
    name: "Elegance By Zara",
    email: "zara@elegance.com",
    avatar: "/stylist-avatar-5.jpg",
    company: "Elegance By Zara",
    role: "stylist",
    verificationStatus: "verified",
    status: "active",
    totalProducts: 42,
    pendingApproval: 2,
    totalOrders: 189,
    totalRevenue: 1850000,
    rating: 4.7,
    reviewCount: 134,
    joinedDate: "2023-09-05T09:45:00Z",
    lastLogin: "2024-03-20T16:10:00Z",
    isEmailVerified: true,
    canAddProducts: true,
    businessInfo: {
      description: "Elegant and sophisticated fashion for modern women",
      location: "Lagos, Nigeria",
      experience: "6 years",
      specialties: ["Elegant", "Sophisticated", "Corporate"],
    },
  },
];

// Mock data
export const products = [
  {
    id: "f1",
    name: "Royal Kente Agbada Set",
    slug: "royal-kente-agbada",
    image: "/featured-1.jpg",
    price: 65000,
    originalPrice: 80000,
    stylist: "Royal Heritage Designs",
    colors: ["gold", "red", "black"],
    rating: 5.0,
    reviews: 342,
    isBestSeller: true,
    isNew: false,
    description: "Handwoven kente fabric with intricate embroidery details",
    category: "men",
    type: "native",
  },
  {
    id: "f2",
    name: "Premium Silk Adire Gown",
    slug: "premium-silk-adire",
    image: "/featured-2.jpg",
    price: 55000,
    originalPrice: 68000,
    stylist: "Amina Luxury",
    colors: ["indigo", "white", "gold"],
    rating: 4.9,
    reviews: 278,
    isBestSeller: true,
    isNew: true,
    description: "Luxury silk adire with hand-painted patterns and lace accents",
    category: "women",
    type: "native",
  },
  {
    id: "f3",
    name: "Modern Ankara 3-Piece",
    slug: "modern-ankara-3piece",
    image: "/featured-3.jpg",
    price: 48000,
    originalPrice: 55000,
    stylist: "Urban African Couture",
    colors: ["blue", "yellow", "green"],
    rating: 4.8,
    reviews: 195,
    isBestSeller: false,
    isNew: true,
    description: "Contemporary take on traditional Ankara with modern tailoring",
    category: "unisex",
    type: "casual",
  },
  {
    id: "f4",
    name: "Beaded Asooke Evening Dress",
    slug: "beaded-asooke-evening",
    image: "/featured-4.jpg",
    price: 72000,
    originalPrice: 85000,
    stylist: "Zainab Royalty",
    colors: ["cream", "gold", "burgundy"],
    rating: 5.0,
    reviews: 421,
    isBestSeller: true,
    isNew: false,
    description: "Hand-beaded asooke fabric with crystal embellishments",
    category: "women",
    type: "native",
  },
  {
    id: "f5",
    name: "African Print Office Suit",
    slug: "african-print-office-suit",
    image: "/featured-5.jpg",
    price: 38000,
    originalPrice: 45000,
    stylist: "Corporate Afrique",
    colors: ["navy", "gray", "black"],
    rating: 4.7,
    reviews: 156,
    isBestSeller: false,
    isNew: false,
    description: "Professional suit with African print accents",
    category: "unisex",
    type: "corporate",
  },
  {
    id: "f6",
    name: "Traditional Yoruba Agbada",
    slug: "yoruba-agbada",
    image: "/featured-6.jpg",
    price: 58000,
    originalPrice: null,
    stylist: "Heritage Weaves",
    colors: ["white", "blue", "gold"],
    rating: 4.9,
    reviews: 287,
    isBestSeller: true,
    isNew: false,
    description: "Authentic Yoruba agbada with intricate embroidery",
    category: "men",
    type: "native",
  },
];
